### ISSUE TITLE
MultiCloudImages Commit Action Missing.

### ISSUE THREAD

**Issue by nguyenja** [rightscale/right_api_client#105]
When using right_api_client on MultiCloudImages resource, the action Commit is missing.  Below are the available methods when you run api_methods on the MultiCloudImages resource.

links
clone
settings
name
description
revision
href
destroy
update
show

**Comment by douglaswth** [comment]
I just tried using `mci.commit(commit_message: 'Test commit')` on an MCI and it worked fine.

**Comment by nguyenja** [comment]
You are correct. I've just tested.  Commit does work.  I didn't try it because it was not listed as an action for that resource.
