### ISSUE TITLE
Refactoring of Gemfile needed

### ISSUE THREAD

**Issue by justingaylor** [rightscale/right_api_client#67]
There seems to be some strangeness in the current [Gemfile](https://github.com/rightscale/right_api_client/blob/427db48cfc1545970ef215cc2bc4c472776ff4db/Gemfile).

In particular, the test gems appear to be in the `:development` group and the development gems appear to be in the `:test` group. This should be fixed and tests should be run to confirm nothing breaks.

We should also ignore .travis.yml, .rspec, and spec/* when building the gemspec.

**Comment by rshade** [comment]
This is probably closed on master right?

**Comment by justingaylor** [comment]
Yeah, thanks @rshade. Closing.
