### ISSUE TITLE
Can't create deployments using @api.send

### ISSUE THREAD

**Issue by Blackbaud-JosephZelada** [rightscale/right_api_client#95]
I'm trying to create deployments using @api.send with no luck. I would assume that if it failed it would return some sort error code or message, but I get nothing back. Am I doing anything in particular wrong with this creation step?
response = @api.send("deployments","post",params)

**Comment by douglaswth** [comment]
I don't think that you are supposed to use that call directly. To create a deployment usually you would do:

```ruby
@api.deployments.create(params)
```
